31 file part3advanced ufunc
pangeo-data/pangeo-openeo-BiDS-2023 pull request #91
Opened 2023-11-04 02:55 UTC by tinaok

2023-11-04 15:03 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>Maybe would be nice to use the same approach I used in the notebook for warnings just to be more consistent</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/91/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2023-11-04 15:03 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>If you didn't test the time and have numbers I would suggest to add a statement that where you at least make users aware that in some cases apply Ufunc can be slower that the usual approach. </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/91/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='50'/>

2023-11-04 15:03 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>Here I would suggest to be more clear about what the UFunc does. Below the description from the documentation.</p><p> </p><p>"Apply a vectorized function for unlabeled arrays on xarray objects.</p><p> </p><p>The function will be mapped over the data variable(s) of the input arguments using</p><p>xarray’s standard rules for labeled computation, including alignment, broadcasting,</p><p>looping over GroupBy/Dataset variables, and merging of coordinates. "</p><p> </p><p>It's not only a matter of mapping over the chunks </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/91/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='52'/>

2023-11-04 15:03 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>I would also change a little bit the scope otherwise could be boring like hell see all the time the same stuff.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/91/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='53'/>

2023-11-04 15:28 UTC, acocac commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
I agree it would be beneficial to add further explanation.

2023-11-04 15:32 UTC, acocac requested changes
@tinaok all ok running the notebook in Pangeo-EOSC, however it seems it fails to build in the Jupyter book. 

I'd suggest add a if/else statement that detects if the environment has dask.gateaway installed, otherwise run the dask.distributed.

2023-11-05 14:23 UTC, tinaok commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
In this notebook, we 'introduce' apply_ufunc, and in next OpenEO part it comes back to it. So I left it in 'light'.  Please go ahead for adding explanation if you have one to make users understand better.

2023-11-05 15:18 UTC, keewis commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
To explain `apply_ufunc`, it is important to note that it takes a function that works with numpy-like arrays and wraps it to support `xarray` objects. In case of a reduction, this means that the original function takes `axis` numbers instead of dimension names.

If you're looking for a more comprehensible explanation, https://tutorial.xarray.dev/advanced/apply_ufunc/simple_numpy_apply_ufunc.html is the place to look.

2023-11-05 18:19 UTC, keewis commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>maybe this?</p><blockquote>* here we use <code>xarray.apply_ufunc</code> to apply the function written for numpy-like arrays to the <code>xarray.DataArray</code> object. Note that the function is composed of element-wise functions and thus can be directly applied to the underlying <code>dask</code>arrays.<span class="ql-cursor">﻿</span></blockquote>

2023-11-05 18:21 UTC, keewis commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>also, I would use <code>np.isin</code> instead of comparing all array values with <code>8</code>,<code>9</code> and <code>3</code> separately for the mask     </p><p> </p>

2023-11-05 18:21 UTC, keewis commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
<p>my github nick is @keewis, could you correct that, please?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/pangeo-data/pangeo-openeo-BiDS-2023/pull/91/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2023-11-05 18:37 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
> To explain `apply_ufunc`, it is important to note that it takes a function that works with numpy-like arrays and wraps it to support `xarray` objects. In case of a reduction, this means that the original function takes `axis` numbers instead of dimension names. "vectorized" itself is not that important (though it does make a difference performance-wise), that's what the `vectorize` parameter takes care of.

for that reason I'm pushing to use a different example but I don't think that we have time

2023-11-05 18:38 UTC, tinaok commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
@keewis please make updates you've suggested, thank you

2023-11-05 18:38 UTC, pl-marasco commented on tutorial/part3/data_exploitability_pangeo.ipynb
>   "cells": [
@keewis I will add the resource you suggested at the top

2023-11-06 07:26 UTC, acocac approved these changes

2023-11-06 12:01 UTC, merged